JDBC_PARAMS: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowMultiQueries=true
server:
  port: 8869
spring:
  datasource:
    url: ${SQLITE_URL:jdbc:sqlite:file:./attachments/db/gen-copilot.db}
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 2MB    # 单个文件最大1MB
      max-request-size: 10MB # 请求最大10MB
  main:
    allow-circular-references: true # 允许循环引用
#  cache:
#    type: caffeine
#    cache-names: token,tableCfgOptions
#    caffeine:
#      spec: maximumSize=50,expireAfterAccess=5m,expireAfterWrite=5m # token缓存最大50个,5分钟内未访问过期,5分钟内未写入过期
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dororo.future.gencopilot.domain

logging:
  level:
    org.apache.ibatis: DEBUG
    org.mybatis.spring.SqlSessionFactoryBean: DEBUG